const userDummy = [
  {
    _id: "1",
    username: "gg",
    firstName: "aaa",
    lastName: "aaa",
    address: "aaa",
    phone: 1234,
    registerNumber: "aaa",
    sisiId: "aaa",
    age: 23,
    gender: "aaa",
  },
  {
    _id: "2",
    username: "dd",
    firstName: "bbbb",
    lastName: "bbbb",
    address: "bbbb",
    phone: 12345,
    registerNumber: "bbbb",
    sisiId: "bbbb",
    age: 24,
    gender: "bbbb",
  },
  {
    _id: "3",
    username: "oo",
    firstName: "cccc",
    lastName: "cccc",
    address: "cccc",
    phone: 123456,
    registerNumber: "cccc",
    sisiId: "cccc",
    age: 24,
    gender: "cccc",
  },
];

export { userDummy };
